version: "3.9"
services:
  system-service:
    image: carodaems/song-api-db
    ports:
      - "8000:8000"
    volumes:
      - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume:
